Feature/unit tests (#74)
* Add basic unit tests and mock client

* More tests passing

* Add bloom filter tests

* Run tests in CI

* Client tests with ws injection, include @zv's coverage work

* Replace assert with if statement, is checking invariant so its fine but codewhatever bot is complaining

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,52 +6,59 @@ services:
 
 
 stages:
-
+  - test
   - e2e
   - prebuildwindows
   - buildwindows
   - notifydependents
 
+test:
+  image: python:3.5
+  stage: test
+  before_script:
+    - pip install tox
+  script:
+    - tox -e py35
 
 kick-e2e:
-    tags:
-        - docker
-    before_script:
+  tags:
+      - docker
+  before_script:
     - apk --no-cache add curl jq unzip py3-requests
     - curl https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip > packer.zip
     - unzip -d /usr/bin/ packer.zip
-    stage: e2e
-    script:
-      - set -e
+  stage: e2e
+  script:
+    - set -e
 
-      # kick e2e
-      - >-
-        E2E_PIPELINE_ID=`curl
-        --silent
-        --request POST
-        --form "token=$CI_JOB_TOKEN"
-        --form "variables[SOURCE_PROJECT]=$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
-        --form "variables[SOURCE_BRANCH]=$CI_COMMIT_REF_NAME"
-        --form ref="master"
-        "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/trigger/pipeline" | jq -r ".id"`
+    # kick e2e
+    - >-
+      E2E_PIPELINE_ID=`curl
+      --silent
+      --request POST
+      --form "token=$CI_JOB_TOKEN"
+      --form "variables[SOURCE_PROJECT]=$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
+      --form "variables[SOURCE_BRANCH]=$CI_COMMIT_REF_NAME"
+      --form ref="master"
+      "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/trigger/pipeline" | jq -r ".id"`
 
-      # poll for it to finish
-      - >-
-        while [ -z $PIPELINE_STATUS ] || [ $PIPELINE_STATUS = "pending" ] || [ $PIPELINE_STATUS = "running" ]; do
-          PIPELINE_STATUS=`curl \
-            --silent \
-            --header "PRIVATE-TOKEN: $CI_CUSTOM_CI_PAT" \
-            "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/pipelines/$E2E_PIPELINE_ID" | jq -r ".status"`
-          echo "waiting for e2e pipeline ...";
-          sleep 5;
-        done
+    # poll for it to finish
+    - >-
+      while [ -z $PIPELINE_STATUS ] || [ $PIPELINE_STATUS = "pending" ] || [ $PIPELINE_STATUS = "running" ]; do
+        PIPELINE_STATUS=`curl \
+          --silent \
+          --header "PRIVATE-TOKEN: $CI_CUSTOM_CI_PAT" \
+          "https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_E2E}/pipelines/$E2E_PIPELINE_ID" | jq -r ".status"`
+        echo "waiting for e2e pipeline ...";
+        sleep 5;
+      done
 
-      # check for success
-      - >-
-        if [ $PIPELINE_STATUS != "success" ]; then
-          echo "failure further down the pipeline"
-          exit 1
-        fi
+    # check for success
+    - >-
+      if [ $PIPELINE_STATUS != "success" ]; then
+        echo "failure further down the pipeline"
+        exit 1
+      fi
 
 wheels:
   stage: prebuildwindows
@@ -66,22 +73,20 @@ wheels:
 
 # OR - pip wheel -r requirements.txt
 packer:
-    before_script:
-      - apk --no-cache add curl jq unzip py3-requests
-      - curl https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip > packer.zip
-      - unzip -d /usr/bin/ packer.zip
-    tags:
-      - docker
-    stage: buildwindows
+  before_script:
+    - apk --no-cache add curl jq unzip py3-requests
+    - curl https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip > packer.zip
+    - unzip -d /usr/bin/ packer.zip
+  tags:
+    - docker
+  stage: buildwindows
 
-    only:
-      - feature/windows-builds
-      - master
-    script:
-      - set -e
-      - packer build -debug template.json
-
-
+  only:
+    - feature/windows-builds
+    - master
+  script:
+    - set -e
+    - packer build -debug template.json
 
 kickafterpacker:
   before_script:
